# Site settings
title: Nebula Technologies
email: nebula@nebula.gr
description: > # this means to ignore newlines until "baseurl:"
  Trusted local technology partner for laptop repair, PC maintenance, and IT solutions in Komotini.

baseurl: ""
url: "https://nebula.gr"

# Build settings
markdown: kramdown
